### ISSUE TITLE
Support libpango

### ISSUE THREAD

**Issue by h2non** [marcbachmann/dockerfile-libvips#3]
libvips [uses](https://github.com/jcupitt/libvips#pangoft2) [pango](http://www.pango.org) for text-based rendering, for instance to create watermark in images via `vips_text()`.

It would be great if the Dockerfile installs `libpango` and configure it properly via `pkg-config` by default.

**Comment by marcbachmann** [comment]
So do I only need `libpango`? You mentioned `libpangoft2` here: https://github.com/jcupitt/libvips/issues/336 :wink:

**Comment by marcbachmann** [comment]
> It would be great if the Dockerfile installs libpango and configure it properly via pkg-config by default.

If that was supposed to be a question, yes, we can add it.
I'm building right now.

**Comment by h2non** [comment]
You're right. Technically `libpangoft2` is usually a dependency of `libpango` in `apt`. 
Perhaps it's only required to install [libpango1.0-dev](http://packages.ubuntu.com/trusty/amd64/libpango1.0-dev).

**Comment by h2non** [comment]
I guess that adding the following statement before compiling `libvips` should be enough:

``` dockerfile
RUN apt-get update && apt-get install -y libpango1.0-dev
```

**Comment by h2non** [comment]
Then you should see what John is pointing about during the compilation:

```
text rendering with pangoft2:       yes
```

**Comment by marcbachmann** [comment]
Building on my machine... damn. too slow.
Now building on a server.
`checking for PANGOFT2... yes`

The build is now complete.
But there are 4 other messages. Maybe I can also add them.

```
configure: OpenSlide >= 3.4.0 not found; checking for >= 3.3.0
checking for OPENSLIDE... no
configure: WARNING: OpenSlide >= 3.3.0 not found; disabling virtual slide support
checking for MATIO... no
configure: WARNING: matio not found; disabling matio support
checking for CFITSIO... no
configure: WARNING: cfitsio not found; disabling cfitsio support
configure: WARNING: pygobject-3.0 not found; disabling vips8 python support
```

**Comment by h2non** [comment]
OpenSlide is highly recommended too. It would be great to have support for it. Also for `libtiff`.

**Comment by h2non** [comment]
I've just compiled it as well using a modified version of your Docker and it works.

**Comment by h2non** [comment]
Do you have plans to release a new tag today?

**Comment by marcbachmann** [comment]
yep. Should I do that using the same tag or a new one? I've seen that on github there's v8.0.3. But I still don't understand that versioning of libvips :)

**Comment by h2non** [comment]
I guess that if you do not bump the version in some way of your image, Docker client won't fetch a fresh image. That's the unique big constrain probably.

**Comment by h2non** [comment]
Perhaps you can bump directly the minor to work with `8.1.0`. It's stable too.

**Comment by h2non** [comment]
IMHO we can release a new tag of the same `libvips` version, but adding the semver compatible metadata build number, e.g: `8.0.2-1`.
Alternatively, you can bump directly the minor and release a new tag using `libvips` 8.1.0 and the changes you introduced to cover this feature.

**Comment by marcbachmann** [comment]
Pushing 8.1.0 is easier. 8.0.2-1 might be confusing for other people.
Now everything in the image except `cfitsio`.
I have no idea how to install that on ubuntu 14.04.
apt-get is not working for `libcfitsio-dev` and `libcfitsio`.

And python bindings are excluded in the build since the beginning. I can enable that later if somebody requests it.

**Comment by h2non** [comment]
Excellent. I'll try pulling the latest image and I'll let you know.

**Comment by h2non** [comment]
Ouch, I'm going too fast. If you don't mind let me know when you pushed the version to Docker hub.

**Comment by marcbachmann** [comment]
:smile: Everything is online. https://hub.docker.com/r/marcbachmann/libvips/tags/

**Comment by marcbachmann** [comment]
Thanks for the help

**Comment by h2non** [comment]
Brilliant. All is working now as expected. Thank you.

**Comment by marcbachmann** [comment]
You're welcome.
Hehe. I was browsing your project. You're building an image service named `imaginary`.  I almost named my service like that. :smile:
I was doing something in node.

**Comment by h2non** [comment]
haha! That name is definitively a good one, and inspiring too :laughing:
