### ISSUE TITLE
New version of libvips

### ISSUE THREAD

**Issue by jyounus** [marcbachmann/dockerfile-libvips#5]
Hey there,

There's a newer version of libvips out and would appreciate it if you could update your repo and push an update to docker hub as well.

I need version 8.2.3 as a minimum for a library (http://sharp.dimens.io/en/stable/changelog/#v014-needle).

Thank you.

**Comment by marcbachmann** [comment]
I just pushed v8.2.3. Thanks for the notification.

**Comment by jyounus** [comment]
Perfect, thank you for the quick update! :D
