### ISSUE TITLE
New libvips version

### ISSUE THREAD

**Issue by jyounus** [marcbachmann/dockerfile-libvips#6]
Hey there,

It's me again, any chance you could please update it to the latest version of libsvips?
I need v8.3.1 as a minimum for the latest update of a module that I'm using: http://sharp.dimens.io/en/stable/changelog/#v015-outfit

Thanks :)

**Comment by h2non** [comment]
Also, there is v8.4. Versions from 8.3+ support GIF, SVG and PDF image processing with the proper library bindings during compilation, so it would be a very nice-to-have support for it in this image.

**Comment by marcbachmann** [comment]
oh, nice. I believe 8.4 is the dev version now. The versioning is a bit strange in that project.

**Comment by h2non** [comment]
Having libvips@8.3 available in Docker would be enough, since it provides the features commented before.

**Comment by marcbachmann** [comment]
Will upgrade to 8.4.2. 
They state that's the supported version: http://www.vips.ecs.soton.ac.uk/index.php?title=Supported#About_vips-8.4

**Comment by marcbachmann** [comment]
v8.4.1 is pushed as `marcbachmann/libvips:8.4.1` and `marcbachmann/libvips:latest`.
I guess 8.4.2 is really still in development. I couldn't find a tar file for that.
