### ISSUE TITLE
SVG, PDF and GIF support

### ISSUE THREAD

**Issue by h2non** [marcbachmann/dockerfile-libvips#8]
`libvips` from version `8.3+` supports GIF, SVG and PDF image inputs if it's properly linked against required third-party libraries during compilation.

Those libraries are:
- `librsvg` for SVG processing
- `giflib` for GIF processing
- `libpoppler` for PDF processing

It would be nice if the Docker image installs and compiles `libvips` accordingly in order to support those image formats.

**Comment by marcbachmann** [comment]
I've added giflib and libpoppler in 8.4.1.
I didn't see a warning regarding librsvg. So I didn't know about it and didn't add it.

**Comment by h2non** [comment]
It would very convenient having `SVG` support as well... 
You can release a new tag as `8.4.1-1` or `8.4.1+1` to keep the native version intact without breaking the `semver` convention.

**Comment by marcbachmann** [comment]
I directly pushed to master. Docker hub will build it and publish if it (as `latest`) was successful.
I'll update the tag once that ran through.
https://github.com/marcbachmann/dockerfile-libvips/commit/8f1a1ec8a7e8301bd633975c3a2b638751164234

**Comment by h2non** [comment]
Cool, thank you! Moreover, I think libvips 8.4 can be considered stable today.
